### ISSUE TITLE
docker: Error response from daemon:

### ISSUE THREAD

**Issue by Geisianny** [pselvana/VoiceCrafter#1]
When trying to run your code, I encountered the following error:

docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'  
nvidia-container-cli: initialization error: WSL environment detected but no adapters were found: unknown.

 I am using the Windows system.

**Comment by pselvana** [comment]
Hello - that looks like a WSL error specific to your Windows and Docker setup.
This might help: https://github.com/NVIDIA/nvidia-container-toolkit/issues/155

Essentially if the following test command fails with the same error then this repo won't work for you either:
```sh
sudo docker run --rm --gpus all nvidia/cuda:11.6.1-base-ubuntu20.04 nvidia-smi.
```
Various solutions include:
- Upgrading Windows 10 to at least 21H2
- Using the latest Nvidia drivers
- Updating to the newest Docker Desktop version; if at latest, going back to another version that might work
- Restarting the machine
- Update latest WSL by running `wsl --update`

Also, what Nvidia Graphics card, Windows version and Nvidia Driver version do you have installed?

Good luck!
